name: Eminence Label Managers
description: Manage repository labels with JSON
author: Xeffen25

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: tag
  color: red

# Define your inputs here.
inputs:
  token:
    description: Your token
    required: true

runs:
  using: node20
  main: dist/index.js
